name:first-yaml
on:push
jobs: 
    build:
         name: Fisrt job
         run-on: umbutu-latest
         steps:
              -name: Step one
               uses: Action/Checkout@v2
               -name: Step two
                run: env | sort  
       build:
           name: Second job
           run-on: windows-latest
           steps:
                -name: Step one
                 uses: Action/Checkout@v2
                -name: Step two
                  run: "Get-ChildItem Env: | Sort-Object Name"
