name:first
on:push
jobs:
    job1:
         name: Fisrt job
         runs-on: umbutu-latest
         steps:
              -name: Step one
               uses: Action/Checkout@v2
               -name: Step two
               run: env | sort  
       job2:
           name: Second job
           runs-on: windows-latest
           steps:
                -name: Step one
                 uses: Action/Checkout@v2
                -name: Step two
                  run: "Get-ChildItem Env: | Sort-Object Name"
