# This is a basic workflow to help you get started with Actions

name:first
on:push
    branches:
      - 'autoupdate'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -  run: echo Test One Worked!
